name: Deployment pipeline

on:
  push:
    branches:
      - main
      
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}

jobs:
  predeployment_tasks:    
    runs-on: ubuntu-20.04    
    steps:      
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3        
        with:          
          node-version: '16'
      - name: npm install        
        run: npm install
      - name: lint        
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start-test
          wait-on: http://localhost:3001
  deploy: 
    if: ${{ !contains(toJson(join(github.event.commits.*.message, ' ')), '#skip') && github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    needs: [predeployment_tasks]
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: deploy app
      run: flyctl deploy --remote-only 
    - name: send success notification
      uses: rjstone/discord-webhook-notify@v1
      if: ${{ success() && github.event_name == 'push' }}
      with:
        severity: info
        description: 'Commit ${{ github.sha }}'
        details: Build succeeded.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}        
    - name: send failure notification
      uses: rjstone/discord-webhook-notify@v1
      if: ${{ failure() && github.event_name == 'push' }}
      with:
        severity: error
        description: 'Commit ${{ github.sha }}'
        details: Build failed.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}  
  tag_releases:
    if: ${{ !contains(toJson(join(github.event.commits.*.message, ' ')), '#skip') && github.event_name == 'push' }}
    needs: [deploy]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
